language: python
dist: xenial
matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "pypy3"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - py.test
  - tools/ion-hash
